<?php
/**
 * @author  XiaohuiTian.
 * email: tianxh@jpgk.com.cn
 * QQ:2018997757 * Date: 2016/3/23
 * Time: 17:12
 */

namespace IMooc\Decorator;


/**
 * Class Concrete2Decortor
 *
 *
 * @package IMooc\Decorator
 */
class Concrete2Decortor extends Decorator
{
	public function __construct(Component $component)
	{
		parent::Decorator($component);
	}

	public function operate()
	{
		parent::operate(); // TODO: Change the autogenerated stub

		$this->decorator1();
	}

	private function decorator1(){

		echo "装饰器2的装饰方法1！\n";
	}
}